language: perl

script: 
  - prove -lr t
  - cover -test -report coveralls

perl:
#  - "blead"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
  - cpanm -n Devel::Cover
  - cpanm -n Devel::Cover::Report::Coveralls
  - cpanm -n Test::Perl::Critic

